language: python
cache: pip
python:
  - 3.6

matrix:
  fast_finish: true

script: python3 app.py
deploy: 
  provider: heroku
  api_key: $HEROKU_TOKEN

notifications:
  email:
    on_success: never
    on_failure: always