language: python
python:
  - '3.6'
deploy:
  provider: heroku
  api_key:
    secure: eYIPL+IA8psa5T6YJzUvSbFZuFwJuQ5NkSMMYr6fONxZRuZ3T2pZSWAFSQLae3IDl7lxmvXEr5tObBqN+43rdjB3uFbFQIDs6t5m0tJqN8PDcMelKOjPepHNp6zz7Bp5rx29FY/Qt22yurndVSkW0zFXyh6ZTzgyP6pLHw7KVM8wmdPlTT/vL+uyBF5GIVaYrMyNhbW1QRFxwqAbymXwBDhLHDqxk1m46J1K5HVs7hBoGARB2iKpJTxHOEqtOLYN0ypWSdDzh66YPdfe0LHQXd7QCqD+ODswns8ljkl406aMBQdbmbpocpvbQWEQtDm00n4SOS30/cK+H7ijTItYv8N9DeIECuwYUsCDnzrjcxBImMxW4BTEkthvJ8bY4K9yegF4rL0bcz7imkkx2/4fz1fSqWvRi91fM3YrVJJFGnaGP44L9cYxp9frisrNqvYh7ad+0wK6Lymz/p09K2Jo/jFvtAYsTCdMF3/TfQ8eHEzvVf7dfE5CITbY9PIn8RPRDnV+CPbri5YFi+lem+3SjRCrS9sDHTTXhmwIburFysdcH0sn7K8WjGOD3nGpI3Rm2hKTw6eQC3lPLOZJVvo9TitdWTdack2ftVeSml6MYqlVQ93X/9beBjegvZAVBaJU52ctwdM8W2ElmAnrhMpahdhYBxsus6L9MshAmNWNd0M=
